// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configuration.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CookieRequest struct {
	JwtToken             string   `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CookieRequest) Reset()         { *m = CookieRequest{} }
func (m *CookieRequest) String() string { return proto.CompactTextString(m) }
func (*CookieRequest) ProtoMessage()    {}
func (*CookieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{0}
}

func (m *CookieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CookieRequest.Unmarshal(m, b)
}
func (m *CookieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CookieRequest.Marshal(b, m, deterministic)
}
func (m *CookieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CookieRequest.Merge(m, src)
}
func (m *CookieRequest) XXX_Size() int {
	return xxx_messageInfo_CookieRequest.Size(m)
}
func (m *CookieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CookieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CookieRequest proto.InternalMessageInfo

func (m *CookieRequest) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type UserInfoResponse struct {
	Valid                bool      `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User                 *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{1}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *UserInfoResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UserInfo struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,2,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Id                   float64  `protobuf:"fixed64,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_415c9e57263f32ab, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *UserInfo) GetId() float64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CookieRequest)(nil), "protobuf.CookieRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "protobuf.UserInfoResponse")
	proto.RegisterType((*UserInfo)(nil), "protobuf.UserInfo")
}

func init() { proto.RegisterFile("configuration.proto", fileDescriptor_415c9e57263f32ab) }

var fileDescriptor_415c9e57263f32ab = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4f, 0xcb, 0x4e, 0xeb, 0x30,
	0x14, 0xbc, 0xee, 0x05, 0xe4, 0xba, 0xe2, 0x21, 0x83, 0x44, 0xd5, 0x6e, 0xaa, 0x2c, 0x50, 0x17,
	0xc8, 0x42, 0xe5, 0x0f, 0x5a, 0x16, 0xb0, 0x8b, 0x0c, 0x11, 0xcb, 0x2a, 0x4d, 0x4e, 0x1a, 0x37,
	0xae, 0x4f, 0xb0, 0x1d, 0xc2, 0xe7, 0xa3, 0xb8, 0x04, 0x84, 0xc4, 0xca, 0x33, 0x63, 0x7b, 0x1e,
	0xec, 0x32, 0x43, 0x53, 0xa8, 0x6d, 0x63, 0x53, 0xaf, 0xd0, 0x88, 0xda, 0xa2, 0x47, 0x4e, 0xc3,
	0xb1, 0x69, 0x8a, 0xe8, 0x96, 0x9d, 0xae, 0x10, 0x2b, 0x05, 0x12, 0xde, 0x1a, 0x70, 0x9e, 0x4f,
	0xd9, 0x70, 0xd7, 0xfa, 0xb5, 0xc7, 0x0a, 0xcc, 0x98, 0xcc, 0xc8, 0x7c, 0x28, 0xe9, 0xae, 0xf5,
	0x2f, 0x1d, 0x8f, 0x62, 0x76, 0x91, 0x38, 0xb0, 0x4f, 0xa6, 0x40, 0x09, 0xae, 0x46, 0xe3, 0x80,
	0x5f, 0xb1, 0xe3, 0xf7, 0x54, 0xab, 0x3c, 0x3c, 0xa6, 0xf2, 0x40, 0xf8, 0x0d, 0x3b, 0x6a, 0x1c,
	0xd8, 0xf1, 0x60, 0x46, 0xe6, 0xa3, 0x05, 0x17, 0x7d, 0xa0, 0xf8, 0xfe, 0x1f, 0xee, 0xa3, 0x67,
	0x46, 0x7b, 0x85, 0x4f, 0x18, 0x35, 0x2a, 0xab, 0x4c, 0xba, 0x87, 0x3e, 0xb9, 0xe7, 0x5d, 0xad,
	0xba, 0x44, 0x8f, 0xeb, 0xc6, 0xea, 0x60, 0x3a, 0x94, 0x34, 0x08, 0x89, 0xd5, 0xfc, 0x8c, 0x0d,
	0x54, 0x3e, 0xfe, 0x3f, 0x23, 0x73, 0x22, 0x07, 0x2a, 0x5f, 0x24, 0xfd, 0xa8, 0x55, 0x09, 0x59,
	0x05, 0x96, 0x3f, 0xb0, 0x51, 0x80, 0x07, 0x95, 0x5f, 0xff, 0xd4, 0xf9, 0x35, 0x7e, 0x32, 0xf9,
	0xa3, 0xe7, 0xd7, 0xce, 0xe8, 0xdf, 0xf2, 0x8e, 0x4d, 0x15, 0x8a, 0xad, 0xad, 0x33, 0x01, 0x1f,
	0xe9, 0xbe, 0xd6, 0xe0, 0x44, 0x09, 0x5a, 0x63, 0x8b, 0x56, 0xe7, 0xcb, 0xf3, 0xc7, 0x0e, 0xbf,
	0x76, 0x38, 0xee, 0x5c, 0x62, 0xb2, 0x39, 0x09, 0x76, 0xf7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x49, 0x15, 0x3f, 0x93, 0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CookieCheckerClient is the client API for CookieChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CookieCheckerClient interface {
	CheckCookie(ctx context.Context, in *CookieRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
}

type cookieCheckerClient struct {
	cc *grpc.ClientConn
}

func NewCookieCheckerClient(cc *grpc.ClientConn) CookieCheckerClient {
	return &cookieCheckerClient{cc}
}

func (c *cookieCheckerClient) CheckCookie(ctx context.Context, in *CookieRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/protobuf.CookieChecker/CheckCookie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CookieCheckerServer is the server API for CookieChecker service.
type CookieCheckerServer interface {
	CheckCookie(context.Context, *CookieRequest) (*UserInfoResponse, error)
}

// UnimplementedCookieCheckerServer can be embedded to have forward compatible implementations.
type UnimplementedCookieCheckerServer struct {
}

func (*UnimplementedCookieCheckerServer) CheckCookie(ctx context.Context, req *CookieRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCookie not implemented")
}

func RegisterCookieCheckerServer(s *grpc.Server, srv CookieCheckerServer) {
	s.RegisterService(&_CookieChecker_serviceDesc, srv)
}

func _CookieChecker_CheckCookie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CookieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CookieCheckerServer).CheckCookie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.CookieChecker/CheckCookie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CookieCheckerServer).CheckCookie(ctx, req.(*CookieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CookieChecker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.CookieChecker",
	HandlerType: (*CookieCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckCookie",
			Handler:    _CookieChecker_CheckCookie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configuration.proto",
}
